[package]
name = "evian-math"
description = "Math utilities in evian."
repository = "https://github.com/vexide/evian/"
authors = ["Tropical"]
license = "MIT"
categories = ["science::robotics", "no-std", "mathematics", "embedded"]
keywords = ["vex", "vexide", "vex-robotics", "robotics", "autonomous"]
version = "0.0.1-rc.1"
edition = "2024"

[dependencies]
glam = { version = "0.30.3", default-features = false, features = ["nostd-libm", "scalar-math"] }
vexide = { workspace = true }

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["armv7a-none-eabi"]
